spring.application.name=HelloApp

#email configuration
spring.mail.username=info@caplngo.cscnews.net
spring.mail.port=587
spring.mail.password=Mohan321@@


#database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/HelloApp
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#jwt configuration
jwt.secret=uiewgirgwqehjrkgwqert3t287364927trwygeirtiuywitewyue


#file upload configuration
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


app.base-url=http://localhost:8080/
